### ISSUE TITLE
Initial Test

### ISSUE THREAD

**Issue by yvkrishna** [flow2ml/Flow2ML#10]
Before adding on new features, It would be better to test the codebase till now so that the corrected code can then be reused for implementing new features

**Comment by rubyruins** [comment]
Hi, I would like to work on this. Are there any specific features of code to be tested?

**Comment by yvkrishna** [comment]
yes, we need to test the entire codebase starting with the getClasses method from Data_Loader class. Next all the methods in filters class. Yes there is a procedure for testing the codebase.

**Comment by rubyruins** [comment]
I would be happy to work on this issue! If you could tell me a bit more about the steps for testing the codebase I can start with it.

**Comment by yvkrishna** [comment]
> I would be happy to work on this issue! If you could tell me a bit more about the steps for testing the codebase I can start with it.

There is material available on steps on software testing like unit testing, logging, and much more. After learning them It would be better to start with pytest.

**Comment by rubyruins** [comment]
> > I would be happy to work on this issue! If you could tell me a bit more about the steps for testing the codebase I can start with it.
> 
> There is material available on steps on software testing like unit testing, logging, and much more. After learning them It would be better to start with pytest.

Alright! I'll take a look at how pytest works and how we can use it. Can we connect on Discord when the project channels open for all participants? I can start contributing once we discuss more.

**Comment by yvkrishna** [comment]
> > > I would be happy to work on this issue! If you could tell me a bit more about the steps for testing the codebase I can start with it.
> > 
> > 
> > There is material available on steps on software testing like unit testing, logging, and much more. After learning them It would be better to start with pytest.
> 
> Alright! I'll take a look at how pytest works and how we can use it. Can we connect on Discord when the project channels open for all participants? I can start contributing once we discuss more.

yes, we can connect through discord. 👍

**Comment by rubyruins** [comment]
Sure, thanks. I tried but was unable to find you on Discord, could you give me your handle, please? Mine is @Soumya on the server.

**Comment by yvkrishna** [comment]
> Sure, thanks. I tried but was unable to find you on Discord, could you give me your handle, please? Mine is @soumya on the server.

mine is yvkrishna#7505. I couldn't find yours.

**Comment by rubyruins** [comment]
I've gone through some articles on pytest, so would it be sufficient to work on this issue for GSSOC? I can start and learn more on the way if you could guide me a bit.

**Comment by yvkrishna** [comment]
> I've gone through some articles on pytest, so would it be sufficient to work on this issue for GSSOC? I can start and learn more on the way if you could guide me a bit.

yeah definitely.

**Comment by chebroluharika** [comment]
@yvkrishna @rubyruins I will close this once https://github.com/flow2ml/Flow2ML/issues/32 is fixed.

**Comment by chebroluharika** [comment]
Closing this as associated issue was closed.
