### ISSUE TITLE
Automate model building -- Logistic Regression

### ISSUE THREAD

**Issue by chebroluharika** [flow2ml/Flow2ML#107]
Create a new class for Automating Model Building part
1. Create a method to take model name, activation function and metric to evaluate as inputs from user. Lets say LogisticRegression for this issue.
2. If  its LogisticRegression, use params like 'solver' = ['newton-cg', 'lbfgs', 'liblinear'], ['penalty'] = ['none', 'l1', 'l2', 'elasticnet'], ['C'] = [1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 1, 10, 100], using hyper parameter tuning find best_params among them.
3. Then build model using those best_params and predict on test_data.
4. According to metric provided by user, evaluate it and return that score from the method

Please feel free to add more customizations to make it more automated.

**Comment by ainy-123** [comment]
> Create a new class for Automating Model Building part
> 
> 1. Create a method to take model name and metric to evaluate as inputs from user. Lets say Linear Regression for this issue.
> 2. If  its Linear Regression, use params like 'solver' = ['newton-cg', 'lbfgs', 'liblinear'], ['penalty'] = ['none', 'l1', 'l2', 'elasticnet'], ['C'] = [1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 1, 10, 100], using hyper parameter tuning find best_params among them.
> 3. Then build model using those best_params and predict on test_data.
> 4. According to metric provided by user, evaluate it and return that score from the method
> 
> Please feel free to add more customizations to make it more automated.

I want to work on this issue. Kindly assign this to me.

**Comment by chebroluharika** [comment]
@ainy-123 You are assigned to this. PLease go ahead and work. When can we expect deliverable for this?

**Comment by chebroluharika** [comment]
> @ainy-123 You are assigned to this. PLease go ahead and work. When can we expect deliverable for this?
Because we need to implement many more models like this.

**Comment by ainy-123** [comment]
> @ainy-123 You are assigned to this. PLease go ahead and work. When can we expect deliverable for this?

latest by tomorrow .I will try to finish by today itself.

**Comment by chebroluharika** [comment]
Closing this for time being
