### ISSUE TITLE
Automate model building -- Random Forests

### ISSUE THREAD

**Issue by chebroluharika** [flow2ml/Flow2ML#108]
Create a new class for Automating Model Building part
1. Create a method to take model name and metric to evaluate as inputs from user. Lets say Random Forests for this issue.
2. If  its Random Forests, use params like {"max_depth": [3, None], "max_features": randint(1, 50), "min_samples_leaf": randint(1, 50), "criterion": ["gini", "entropy"]}, using hyper parameter tuning find best_params among them.
3. Then build model using those best_params and predict on test_data.
4. According to metric provided by user, evaluate it and return that score from the method

Please feel free to add more customizations to make it more automated.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by chebroluharika** [comment]
@AshuKV please go ahead and work on this. When can we expect deliverable for this?

**Comment by AshuKV** [comment]
I would deliver a PR for this issue within 4-5 days.

**Comment by chebroluharika** [comment]
Closing this for time being
