### ISSUE TITLE
One-Hot or Numbers (User has to choose)

### ISSUE THREAD

**Issue by yvkrishna** [flow2ml/Flow2ML#112]
As per the code till now, we are getting the outputs of getDataset() method as training data and training labels.

Now we want to add a small functionality that the outputs can be numbers or else one-hot vectors and this has to be chosen by the user.

Based on the user's wish we can either generate output labels as one-hot vectors or else numbers (i.e index of the class names).

**Comment by earnsans** [comment]
Hi, I'm a GSSOC'21  participant, could you please assign this issue to me. Will work on it as soon as possible. Thank you.

**Comment by yvkrishna** [comment]
@earnsans, Yeah, you can work on this.

When can we expect the output?

**Comment by earnsans** [comment]
Thank you :)

**Comment by earnsans** [comment]
Thank you for assigning this to me. 
Can I submit this by 29th may?

**Comment by yvkrishna** [comment]
@earnsans, go ahead but try to complete asap. We (admin and mentor) need some time for managing all the pr's and issues before gssoc deadline.

**Comment by earnsans** [comment]
Yeah sure. I'll  take care of that @yvkrishna

**Comment by yvkrishna** [comment]
@earnsans, any update ?

**Comment by earnsans** [comment]
@yvkrishna  I'm working on it.

**Comment by yvkrishna** [comment]
okay 👍, go ahead

**Comment by earnsans** [comment]
hello @chebroluharika I've  made a PR, but why has the issue been closed?

**Comment by earnsans** [comment]
I was working on this issue , how could someone else's work been merged?

**Comment by Aryamanz29** [comment]
> hello @chebroluharika I've made a PR, but why has the issue been closed?

I think in this  PR #150 @rubyruins tagged the `wrong issue number` that's why this issue been closed 😕 . @yvkrishna Please reopen this one
