### ISSUE TITLE
Implement canny edge detection technique

### ISSUE THREAD

**Issue by ainy-123** [flow2ml/Flow2ML#115]
I am GSSoC'21 participant .I want to work on this issue.
Kindly assign me the same.

**Comment by yvkrishna** [comment]
@ainy-123, that's a filtering technique ryt.

Also a part of that sobelx, sohely have been created in filters.py

**Comment by chebroluharika** [comment]
@ainy-123 we have enough number of filters implemented already. Can you please work on other tasks as they brings more value to our package. Once they are done, you can takeup this and work. Hope I made some sense.

**Comment by yvkrishna** [comment]
I am closing this issue temporarily. Will reopen if needed.
