### ISSUE TITLE
changing the color-space of the image as part of augmentation.

### ISSUE THREAD

**Issue by ainy-123** [flow2ml/Flow2ML#118]
1. from BGR to RGB
2. from BGR to GRAY
3. from GRAY to BGR
4. from GRAY to RGB

**Comment by ainy-123** [comment]
> 1. from BGR to RGB
> 2. from RGB to BGR
> 3. from BGR to GRAY
> 4. from GRAY to BGR
> 5. from RGB to GRAY
> 6. from GRAY to RGB

can I work on this issue under GSSoC'21?

**Comment by chebroluharika** [comment]
@ainy-123 Please work on this after completing existing issues that are assigned to you.

**Comment by chebroluharika** [comment]
@ainy-123 there is already one augmentation technique to convert images into greyscale.
