### ISSUE TITLE
Requirements not updated

### ISSUE THREAD

**Issue by rubyruins** [flow2ml/Flow2ML#121]
### Requirements.txt has issues:

![image](https://user-images.githubusercontent.com/50259869/119237537-f530d100-bb5a-11eb-8f78-be5859d28486.png)

![image](https://user-images.githubusercontent.com/50259869/119237553-08dc3780-bb5b-11eb-8aa6-0963fc7a8103.png)

Pandas and seaborn are not added to requirements.txt

### **To Reproduce:**
I have deleted my venv, created a new one and reinstalled all requirements again to confirm that the error persists.

**Comment by chebroluharika** [comment]
@rubyruins can you work on this

**Comment by rubyruins** [comment]
> @rubyruins can you work on this

Done!
