### ISSUE TITLE
Add welcome bot

### ISSUE THREAD

**Issue by itsIapetus** [flow2ml/Flow2ML#13]
I would like to add a welcome bot for new issues, new prs.
Kindly assign it to me under gssoc, thanks!

**Comment by Sibasish-Padhy** [comment]
i too wanna work on this issue under gssoc 2021.please do consider to assign this issue to me

**Comment by chebroluharika** [comment]
@Sibasish-Padhy Sorry, @itsIapetus already worked on it and raised PR for it.
