### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [flow2ml/Flow2ML#14]
Hi ! I would like to create a file named contributing.md which will 
Add the following -

1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
I would like to work on this as a part of GSSOC'21

**Comment by RiyaVashishtha** [comment]
Hi,  As a GSSOC'21 participant, I would like to contribute to this issue, please assign this issue to me.

**Comment by khareyash05** [comment]
@RiyaVashishtha I am a participant and have self created this issue 
Sorry!

**Comment by khareyash05** [comment]
@yvkrishna  Created a PR Have a look!

**Comment by Dhriti-Roy** [comment]
I am a Gssoc'21 participant , I would like to work on it . Kindly assigned it to me.

**Comment by khareyash05** [comment]
hi @Dhriti-Roy I have self created the issue and also attached a PR . Just waiting for reviewers to review and merge
Sorry1

**Comment by yvkrishna** [comment]
Hello participants, sorry for the late reply. We will be checking each of your pr's. Give us some time. Everyone of us are currently busy with daily works. You can start contributing for other issues. 😃

**Comment by yvkrishna** [comment]
> @RiyaVashishtha I am a participant and have self created this issue
> Sorry!

no problem.

**Comment by RiyaVashishtha** [comment]
No problem
