### ISSUE TITLE
adding contributors profile image with Github handle in readme

### ISSUE THREAD

**Issue by rajeshpanjiyar** [flow2ml/Flow2ML#20]
I want to add the **contributor's** section in the readme file. It is one of the best parts of every readme.
- I am a *participant* in **GSSoC'21**
- I would like to be assigned and start working.

**Comment by yvkrishna** [comment]
Hey @rajeshpanjiyar , Updating readme requires discussion of the mentors and myself. so please try to maintain contribution.md file and put your content over there.

Thanks for choosing this project 😄

**Comment by yvkrishna** [comment]
> Hey @rajeshpanjiyar , Yeah you can work on it.
> 
> Thanks for choosing this project 😄
