### ISSUE TITLE
Color reversal in filters feature

### ISSUE THREAD

**Issue by rubyruins** [flow2ml/Flow2ML#28]
For the example image given below, I applied the filters functionality on it:
![apple_3](https://user-images.githubusercontent.com/50259869/113029885-9aa67480-91aa-11eb-9d85-10c77b08f64a.jpg)

This is the result after applying Gaussian filter on the image:
![gaussianapple_3](https://user-images.githubusercontent.com/50259869/113029951-b1e56200-91aa-11eb-80a0-72690be36a96.jpg)

This is the median filter result:
![Medianapple_3](https://user-images.githubusercontent.com/50259869/113030047-cf1a3080-91aa-11eb-92b7-42e3ef2fd87d.jpg)

The other 3 filters seem to be working fine (Sobelx, Sobely and Laplacian), but for these images there seems to be a colour reversal. If it is a known issue, can I work on this, please?

**Comment by chebroluharika** [comment]
@rubyruins Yes, please go ahead and raise PR with fix after you work on this.

**Comment by rubyruins** [comment]
Thank you, will do
