### ISSUE TITLE
Bug in create_dataset() and prepare_dataset() in DataLoader.py

### ISSUE THREAD

**Issue by chebroluharika** [flow2ml/Flow2ML#32]
There were few fixes needed for DataLoader.py file.
1. Fixing post mentioned error in createDataSet function.

Percent: [##########] 100% Filtered all images in apple ...
Percent: [##########] 100% Filtered all images in banana ...

Percent: [----------] 0.0% Traceback (most recent call last):
  File "tryout.py", line 18, in <module>
    (train_x, train_y, val_x, val_y) = flow.getDataset( img_dimensions, test_val_split )
  File "C:\Users\ACER\Downloads\Flow2ML\flow2ml\Flow.py", line 116, in getDataset
    self.img_label = self.create_dataset(path)
  File "C:\Users\ACER\Downloads\Flow2ML\flow2ml\Data_Loader.py", line 94, in create_dataset
    folderName = list(classPath.split("/"))[2]
IndexError: list index out of range

2. Correcting tulpe to tuple.

3. Create numpy dataset dynamic enough accordingly with loaded image dimensions and number of channels.

**Comment by rubyruins** [comment]
Hi, as discussed last night, I can go ahead with this issue, right?

**Comment by chebroluharika** [comment]
yes, please work on it and raise PR with fix.
