### ISSUE TITLE
Improving code quality

### ISSUE THREAD

**Issue by chebroluharika** [flow2ml/Flow2ML#34]
1. Add exception handling for all scenarios like file management, for loop exhaust, OS management etc.,
2. Add Documentation wherever required.
3. Removed commented code.

**Comment by iamansoni** [comment]
I would like to work on this task, you can assign this issue to me!
Also, it is to be done for all the `.py` files, or is there any specific one that you are addressing to?

**Comment by chebroluharika** [comment]
@iamansoni please work for all .py files indirectly we need to qualify an entire code.

**Comment by chebroluharika** [comment]
@iamansoni Do we have nay update on this?

**Comment by jaswaniyogita** [comment]
@iamansoni any updates or do we assign it to someone else?

**Comment by chebroluharika** [comment]
As there is no proper update, unassigning it.

**Comment by chebroluharika** [comment]
@rubyruins #72 is one of subtasks for this issue.

**Comment by chebroluharika** [comment]
@rubyruins I assigned issue to you. You can start working on it.
