### ISSUE TITLE
Automated unit tests for functionalities

### ISSUE THREAD

**Issue by chebroluharika** [flow2ml/Flow2ML#35]
Now, as we are working in Test Driven Environment, writing unit tests is crucial for any software development.
1. Write unit tests for methods in .py files using pytest or unittest framework.
2. Create github workflow to run those unit tests for every pull-request raised.
3. Make sure that coverage should be above 90%

**Comment by rubyruins** [comment]
I'd like to take up this issue.

**Comment by chebroluharika** [comment]
@rubyruins do we have any update on this?

**Comment by rubyruins** [comment]
Hi, I have started but got held up with college work in between. I'll definitely try to get it done this week 👍
