### ISSUE TITLE
Readme file enhancement

### ISSUE THREAD

**Issue by anirudhsai20** [flow2ml/Flow2ML#40]
The Readme file can be enhanced by adding a list of all the Open Source programs in which this project was listed in.

**Comment by anirudhsai20** [comment]
Hi! Please allow me to work on this issue under GSSOC.

**Comment by chebroluharika** [comment]
hi @anirudhsai20 , READMe file has already dependencies listed. What exactly you mean by Open Source programs

**Comment by anirudhsai20** [comment]
I will add a list of all the Open Source programs that this project is a part of like the GirlScript Summer of Code, DevScript Winter of Code, etc. Something like this:
![pda](https://user-images.githubusercontent.com/63279440/113385306-82e71000-93a5-11eb-80bf-77553c4fbfdd.png)

**Comment by chebroluharika** [comment]
@anirudhsai20 , please go ahead and work on it.

**Comment by anirudhsai20** [comment]
Sure. I will add those as well.

**Comment by anirudhsai20** [comment]
Add by features, do you mean the features of this repository like Low-code, enables fast design and customization of ML work flows, etc. ?
And are these the only two technologies used in this repository? - Python, HTML, Machine Learning ?

**Comment by chebroluharika** [comment]
I think you can add OpenCV also under tech used. @yvkrishna Whats your comment here?

**Comment by yvkrishna** [comment]
> I think you can add OpenCV also under tech used. @yvkrishna Whats your comment here?

yes. It's one of the main packages used.

**Comment by chebroluharika** [comment]
@yvkrishna please mention if there are any other additional tech present?

**Comment by yvkrishna** [comment]
opencv and numpy are the main packages till now.

> @yvkrishna please mention if there are any other additional tech present?

**Comment by anirudhsai20** [comment]
Please let me know whether I am right about the features.
