### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by yvkrishna** [flow2ml/Flow2ML#42]
To create a new Logo for this organization.
Need UI developers.

**Comment by shikha-16** [comment]
Hey! I can do this, please assign it to me!

**Comment by chebroluharika** [comment]
@shikha-16  Please go ahead and work on it.

**Comment by chebroluharika** [comment]
@shikha-16 Please attach screenshots here that you have worked till now. So that everyone can pitch in their ideas.

**Comment by shikha-16** [comment]
Sure @chebroluharika 
![image](https://user-images.githubusercontent.com/68149849/114133062-129b3a00-9923-11eb-8343-270a1589e8ce.png)
![image](https://user-images.githubusercontent.com/68149849/114133107-25ae0a00-9923-11eb-9f5b-b0e2efc2deb9.png)
![image](https://user-images.githubusercontent.com/68149849/114133121-2c3c8180-9923-11eb-80c9-a6d4c1b1c663.png)
![image](https://user-images.githubusercontent.com/68149849/114133133-31013580-9923-11eb-92f1-e9bf7469771a.png)
Please take a look.

**Comment by shikha-16** [comment]
@chebroluharika @yvkrishna please review

**Comment by yvkrishna** [comment]
> @chebroluharika @yvkrishna please review

The final one is looking nice as compared with others. Can you improve the design a bit more. like color and few adjustments.

**Comment by SAHU-01** [comment]
//cc @yvkrishna Here are few of my logo ideas let me know if you like it

![Flow2ML (1)](https://user-images.githubusercontent.com/71656941/114406066-db4bb800-9bc4-11eb-9988-12559c6e224d.png)

![Flow2ML](https://user-images.githubusercontent.com/71656941/114406224-fe766780-9bc4-11eb-935a-1505d5243813.png)

![image](https://user-images.githubusercontent.com/71656941/114406270-07ffcf80-9bc5-11eb-8f0c-3a554e612b3d.png)


Here are some more diffrent wave patterns,if any of the patterns are to your likeing let me know then we can decide a font type and add "Flow2ML" to it


![image](https://user-images.githubusercontent.com/71656941/114406396-22d24400-9bc5-11eb-8ba4-41ca647f24cc.png)

![image](https://user-images.githubusercontent.com/71656941/114406493-367daa80-9bc5-11eb-9af4-d93487dd45d9.png)

![image](https://user-images.githubusercontent.com/71656941/114406558-44333000-9bc5-11eb-8884-a3f4c55854f1.png)

**Comment by yvkrishna** [comment]
@SAHU-01 we are trying to make a logo as part of this issue. your's look like a poster background. we may use them for any ppt.
A logo must look simpler and easily recognizable. I hope you get it.

**Comment by Anushka0483** [comment]
can i work on the same ? if yes , please assign this to me .
@chebroluharika

**Comment by chebroluharika** [comment]
@Anushka0483 goahead and work on it. Lets see whose logo will be final one. Then we will look into assigness section. Sounds good?

**Comment by jaswaniyogita** [comment]
![Blue and White Gaming Logo](https://user-images.githubusercontent.com/69522588/114546422-c03b7f80-9c7a-11eb-9bf7-1bcb9f0d3eba.png)
  
How about this?

**Comment by shikha-16** [comment]
![image](https://user-images.githubusercontent.com/68149849/114554779-b3bc2480-9c84-11eb-950c-e612f5c9c63c.png)
![image](https://user-images.githubusercontent.com/68149849/114554810-bae33280-9c84-11eb-8839-51df7bcd31cf.png)

The watermark will be removed, so do not worry about that. 
Also, since I have been working on this since before, kindly do not assign this to someone else. Thanks

**Comment by yvkrishna** [comment]
> ![Blue and White Gaming Logo](https://user-images.githubusercontent.com/69522588/114546422-c03b7f80-9c7a-11eb-9bf7-1bcb9f0d3eba.png)
> 
> How about this?

I think your's previous one was good

**Comment by yvkrishna** [comment]
> ![image](https://user-images.githubusercontent.com/68149849/114554779-b3bc2480-9c84-11eb-950c-e612f5c9c63c.png)
> ![image](https://user-images.githubusercontent.com/68149849/114554810-bae33280-9c84-11eb-8839-51df7bcd31cf.png)
> 
> The watermark will be removed, so do not worry about that.
> Also, since I have been working on this since before, kindly do not assign this to someone else. Thanks

For me the previous ones looked nice.

**Comment by yvkrishna** [comment]
> > ![image](https://user-images.githubusercontent.com/68149849/114554779-b3bc2480-9c84-11eb-950c-e612f5c9c63c.png)
> > ![image](https://user-images.githubusercontent.com/68149849/114554810-bae33280-9c84-11eb-8839-51df7bcd31cf.png)
> > The watermark will be removed, so do not worry about that.
> > Also, since I have been working on this since before, kindly do not assign this to someone else. Thanks
> 
> For me your's initial ones looked nice.

**Comment by shikha-16** [comment]
![image](https://user-images.githubusercontent.com/68149849/114566746-326a8f00-9c90-11eb-858f-9a07d33fe00b.png)
 This one is with Roboto font

**Comment by jaswaniyogita** [comment]
> ![image](https://user-images.githubusercontent.com/68149849/114554779-b3bc2480-9c84-11eb-950c-e612f5c9c63c.png)
> ![image](https://user-images.githubusercontent.com/68149849/114554810-bae33280-9c84-11eb-8839-51df7bcd31cf.png)
> 
> The watermark will be removed, so do not worry about that.
> Also, since I have been working on this since before, kindly do not assign this to someone else. Thanks

I am a mentor and here just to guide you, so don't worry we aren't assigning it to someone else. I have suggested some changes to you over discord. Please go through those.

**Comment by shikha-16** [comment]
![image](https://user-images.githubusercontent.com/68149849/114751196-7766f200-9d72-11eb-9442-ea5a34681552.png)
![image](https://user-images.githubusercontent.com/68149849/114752821-5901f600-9d74-11eb-9d91-c767bf356f5e.png)
![image](https://user-images.githubusercontent.com/68149849/114751562-eba19580-9d72-11eb-9318-b53039a7476a.png)

**Comment by yvkrishna** [comment]
@shikha-16, I think now you can stop and try to combine it with the ideas of our mentor @jaswaniyogita. She was also having a design with her. I believe you both can combine your ideas.

**Comment by jaswaniyogita** [comment]
We have finalized the logo now. 
This is the logo for Flow2ML
![Blue and White Gaming Logo (1)](https://user-images.githubusercontent.com/69522588/115221391-3df20600-a127-11eb-85bc-d70c95962c8f.png)
