### ISSUE TITLE
Automating Results

### ISSUE THREAD

**Issue by yvkrishna** [flow2ml/Flow2ML#44]
### **Feature request**:
Results are another main part of any machine learning project. Results consist of accuracy-loss plots, confusion matrix,  ROC curves, etc. Flow2Ml focuses on making the entire pipeline of machine learning much easier.  Thus In this feature issue, I propose another idea of automating the results.

### **The Idea**:
A class should be created which contains various methods for various functionalities by taking the trained models as input. With the trained models, the methods should generate various result metrics such as confession matrix, roc curves, etc. With all available result metrics finally, a report.pdf file should be created describing the entire process involved in the workflow.

### **Uses**:
With only a few lines of code, the entire results part could be completed and finally, a report would be generated which can be beneficial to the researchers.

<hr/>

**Side Note:**
If anyone has anything to add to this idea they are free to mention in this thread

**Comment by ArkaprabhaChakraborty** [comment]
Can I work on this?

**Comment by yvkrishna** [comment]
yes you can work on it.

**Comment by chebroluharika** [comment]
@ArkaprabhaChakraborty do we have any update on this?

**Comment by ArkaprabhaChakraborty** [comment]
yes
I have created a class for simple pipelining. I'm working on finalising some stuffs.

**Comment by chebroluharika** [comment]
@ArkaprabhaChakraborty when can we expect the ouput?

**Comment by ArkaprabhaChakraborty** [comment]
By 2nd May, 2021.
