### ISSUE TITLE
Making code compatible enough for non-image datasets

### ISSUE THREAD

**Issue by chebroluharika** [flow2ml/Flow2ML#46]
Need automating functionalities like 

- exploring data, 
- check missing values count, 
- check if there are duplicate values in columns, 
- visualizing features with scatter plots, 
- plot correlation matrix, 
- one hot encoding for target categorical variables if there are any etc.,

which are initial pre-processing steps for non-image data.

Please feel free to add like those steps as apart of this issue which you think they might be useful for text datasets.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSOC21? Kindly assign it to me.

**Comment by yvkrishna** [comment]
yeah, you can start working on it. @AshuKV

**Comment by chebroluharika** [comment]
@AshuKV Do we have any update on this?

**Comment by chebroluharika** [comment]
As there is no response from @AshuKV, unassigning it.
