### ISSUE TITLE
Face_Recognition using KNN

### ISSUE THREAD

**Issue by anubhav201241** [flow2ml/Flow2ML#47]
Hi, I'm a Gssoc'21 participant and want to contribute to your repository
 I want to contribute the face_detection part using Knn Algorithm which detects the face with the help of  KNN algorithm 

@yvkrishna Please assign this part to me

**Comment by chebroluharika** [comment]
@anubhav201241 can you please explain how will this fit into this project

**Comment by anubhav201241** [comment]
@chebroluharika Sure, as KNN is a Machine learning algorithm and this project is about machine learning and python so I thought it will fit because it is also a part of machine learning and as face_detection is a technology used for detecting the face and I use python and Knn in this so that's why I think this is fit for the project. This was my point of view.

**Comment by yvkrishna** [comment]
@anubhav201241 , this package tries to output training, validation datasets. But this package is not used for training any model. Presently it only generates the datasets.

**Comment by anubhav201241** [comment]
Ok sir
