### ISSUE TITLE
Add Examples

### ISSUE THREAD

**Issue by yvkrishna** [flow2ml/Flow2ML#5]
Need to add examples for this library. Users can able to understand the usage of the library if they can have a few examples. 
Also documenting the example code helps.

**Comment by kshittijagrawal** [comment]
Hey there!
I'd like to contribute to the project. I want to address and fix this issue. My implementation will be in python with a clean code and documentation. Kindly provide me with this issue.
I'm also a GSSOC'21 participant.

**Comment by srimontidutta** [comment]
I would like to work on the documentation of this issue for GSSoC 21. Can you please assign it to me?

**Comment by yvkrishna** [comment]
@kshittijagrawal you can start working on it and make a PR. We would look into it.

**Comment by yvkrishna** [comment]
@srimontidutta we can make documentation for examples, but before working on documentation there must be examples. so I can suggest you to write few example codes and then document them.

**Comment by srimontidutta** [comment]
Sure! Then, should I start with it and make a PR or follow any other method so that it can be checked by you beforehand?

**Comment by yvkrishna** [comment]
> Sure! Then, should I start with it and make a PR or follow any other method so that it can be checked by you beforehand?

Yeah, you can start with data augmentation.py file.
https://github.com/flow2ml/Flow2ML/blob/main/flow2ml/Data_Augumentation.py

**Comment by feni-katharotiya** [comment]
@yvkrishna  Hello, I am gssoc participant and would like to work on this issue.

**Comment by yvkrishna** [comment]
I am just adding an example code. It may help in understanding the project. :slightly_smiling_face: 

https://colab.research.google.com/drive/1QPbP3_sSVzKR9kvqdkvXV65OrvCAm5Aj?usp=sharing

**Comment by srimontidutta** [comment]
I'll go through it. Thanks! @yvkrishna

**Comment by Dhriti-Roy** [comment]
I am a Gssoc'21 participant , I would like to work on it . Kindly assigned it to me.

**Comment by yvkrishna** [comment]
> I am a Gssoc'21 participant , I would like to work on it . Kindly assigned it to me.

Yeah you can work on it. We will be assigning members for the second round as there would be selected participants at that time. Anyway the mentor team would discuss on it. Thanks for your participation.

**Comment by vermatanu** [comment]
Hi, can anyone tell me the details required for this? i want to work on this issue 
kindly assign it to me as well

**Comment by yvkrishna** [comment]
@vermatanu Can you try to work with other issues, because there are further improvements going on. so this is not the perfect time to write examples.
