### ISSUE TITLE
Store image array as a class variables

### ISSUE THREAD

**Issue by yvkrishna** [flow2ml/Flow2ML#52]
Up to now, we tried to store processed images as image files in folders, 

This issue focuses on creating a class variable. 
All the images would be stored in the class variable and also folders as input by the user.

**Comment by Saptar001** [comment]
Hello @yvkrishna , can you please elaborate or explain this issue, as I want to work on it for gssoc,21 ??

**Comment by yvkrishna** [comment]
@Saptar001, up to now the images after performing filtering are being saved as separate files in their respective folders. In this issue, I want an implementation such that the image matrices should also be stored as python variables i.e class variables.

**Comment by subhangi2731** [comment]
please assign me this

**Comment by yvkrishna** [comment]
@subhangi2731, let me check with @Saptar001. 

@Saptar001 any updates. You are working on this ryt.

**Comment by Saptar001** [comment]
yess @yvkrishna !

**Comment by yvkrishna** [comment]
@subhangi2731 can you try to solve other issues, we would also post a few more of them 😃

**Comment by chebroluharika** [comment]
@Saptar001 do we have any update on this?

**Comment by Saptar001** [comment]
@chebroluharika yes, and I have shared my work in the discord group flowML 2days back..and also @yvkrishna has seen my work.

Please go through my work out there and give your reviews.

Thank you :)

**Comment by chebroluharika** [comment]
@Saptar001 please raise a PR here, otherwise it will be difficult to validate if its in another way.

**Comment by yvkrishna** [comment]
closing this for time being
