### ISSUE TITLE
Data Augumentation -- Flipping

### ISSUE THREAD

**Issue by yvkrishna** [flow2ml/Flow2ML#56]
This is a sub-issue for #55 

This issue needs to be resolved asap. 

Need to create a method for Data_Augumentation.py file for flipping the image.

**Comment by rubyruins** [comment]
Hi @yvkrishna, I am working on this and have a doubt. In flipping with opencv, we use the argument 0 for flipping on x axis, 1 for flipping on y axis and -1 for flipping on both axis. In this case, when the user applies the technique, should they call it this way

`augmentation_techniques = { flipping:1 }` (can take 1, -1, 0)

or this way

`augmentation_techniques = { flipping:'horizontal' }` (can take 'horizontal', 'vertical' etc.) and then we internally process 'horizontal' to map to flipping with argument 0 and so on. And if we are doing it this way, for flipping on both axis, what word should the user provide? Something like 'both'?

**Comment by yvkrishna** [comment]
> Hi @yvkrishna, I am working on this and have a doubt. In flipping with opencv, we use the argument 0 for flipping on x axis, 1 for flipping on y axis and -1 for flipping on both axis. In this case, when the user applies the technique, should they call it this way
> 
> `augmentation_techniques = { flipping:1 }` (can take 1, -1, 0)
> 
> or this way
> 
> `augmentation_techniques = { flipping:'horizontal' }` (can take 'horizontal', 'vertical' etc.) and then we internally process 'horizontal' to map to flipping with argument 0 and so on. And if we are doing it this way, for flipping on both axis, what word should the user provide? Something like 'both'?

I think It would be better if it is in this way 
`augmentation_techniques = { flipping:'horizontal' }`

**Comment by rubyruins** [comment]
@yvkrishna, okay, so flipping: 'vertical' should map to flip: 0, 'horizontal' maps to flip: 1, and 'cross' should map to flip: -1, right?
