### ISSUE TITLE
Data Augumentation -- Cropping

### ISSUE THREAD

**Issue by yvkrishna** [flow2ml/Flow2ML#59]
This is a sub-issue for #55

This issue needs to be resolved asap.

Need to create a method for Data_Augumentation.py file for Cropping the image.

**Comment by ainy-123** [comment]
I am GSSoC'21 participant .I want to work on this issue.
Kindly assign this to me.

**Comment by yvkrishna** [comment]
I think we can use random cropping technique.

We can use numpy to generate random value between 0 and max_height, max_width and select that region of image. 

You can take Boolean value from user wether to take random crop or not.

**Comment by rubyruins** [comment]
@yvkrishna, oh, okay! So for each image, we would be generating those 4 random coordinates and cropping according to that? Or would we just generate the random coordinates once and then crop each image according to those points? 
Also, if the user selects not to go with the random crop, what should I put in the alternative option? They need to manually give us points to crop?

**Comment by rubyruins** [comment]
Hi, do let me know how to proceed with this so that I can finish working on this!

**Comment by rubyruins** [comment]
@yvkrishna Hi, do let me know how to proceed with it so that I can finish working on this!

**Comment by chebroluharika** [comment]
Yes @rubyruins ask for a boolean value to user. If yes, go with random points else ask them to provide points to crop the image.

**Comment by yvkrishna** [comment]
> Yes @rubyruins ask for a boolean value to user. If yes, go with random points else ask them to provide points to crop the image.

yes, @rubyruins we can expect this kind of behaviour

**Comment by rubyruins** [comment]
> Yes @rubyruins ask for a boolean value to user. If yes, go with random points else ask them to provide points to crop the image.

So for every image will the same set of random points be used or will we generate new ones every time? Also the same with providing points, do we accept a set of points in the start and use that?

**Comment by chebroluharika** [comment]
> > Yes @rubyruins ask for a boolean value to user. If yes, go with random points else ask them to provide points to crop the image.
> 
> So for every image will the same set of random points be used or will we generate new ones every time? Also the same with providing points, do we accept a set of points in the start and use that?

@rubyruins generate new random points everytime and crop image accordingly, visualize them. Ask for a user to continue with the result image if yes, save it in respective folder else ask user to provide points.
