### ISSUE TITLE
Data Augumentation -- Zoom in, Zoom out

### ISSUE THREAD

**Issue by yvkrishna** [flow2ml/Flow2ML#60]
This is a sub-issue for #55

This issue needs to be resolved asap.

Need to create a method for Data_Augumentation.py file for Zooming the image.

**Comment by ainy-123** [comment]
I am GSSoC'21 participant .I want to work on this issue.
Kindly assign this to me.

**Comment by yvkrishna** [comment]
@ainy-123, @rubyruins is already working on this issue i.e data augmentation. You can take up other issues 😃

**Comment by rubyruins** [comment]
@yvkrishna as per the discussion on Discord, do let me know how to proceed with this since you said you might be modifying the zooming / scaling issue!

**Comment by yvkrishna** [comment]
@rubyruins, Sorry for the delay,

You can work on Zooming

**Comment by chebroluharika** [comment]
@rubyruins are you clear with this issue to implement?
