### ISSUE TITLE
Data Augumentation -- scaling

### ISSUE THREAD

**Issue by yvkrishna** [flow2ml/Flow2ML#61]
This is a sub-issue for #55

This issue needs to be resolved asap.

Need to create a method for Data_Augumentation.py file for scaling the image.

**Comment by ainy-123** [comment]
I am GSSoC'21 participant .I want to work on this issue.
Kindly assign this to me.

**Comment by chebroluharika** [comment]
@ainy-123 Please work on #66 firstly. After completion of that, feel free to take up another issue. Because we should give chance to others also right!
Hope you understand.

**Comment by ainy-123** [comment]
> @ainy-123 Please work on #66 firstly. After completion of that, feel free to take up another issue. Because we should give chance to others also right!
> Hope you understand.

Ok thanks! But #66  is not assigned to me,I  think you are talking about #76.

**Comment by chebroluharika** [comment]
@ainy-123 oh! My mistake
Yes, its #76

**Comment by yvkrishna** [comment]
sorry, 
We can work on #60 instead of this one.
