### ISSUE TITLE
Add Examples -Cats Vs Dogs

### ISSUE THREAD

**Issue by yvkrishna** [flow2ml/Flow2ML#62]
Need to add examples for this library. Users can able to understand the usage of the library if they can have a few examples.
Also documenting the example code helps.

Before starting contributing to this issue it is necessary that to complete #55 and its sub-issues.

If data augmentation techniques have also been completed then we can complete this issue.

**Comment by ArkaprabhaChakraborty** [comment]
Anyone working on this? If not then you can assign this to me.

**Comment by chebroluharika** [comment]
@ArkaprabhaChakraborty yes, please go ahead

**Comment by chebroluharika** [comment]
@ArkaprabhaChakraborty when can we expect output for this?

**Comment by ArkaprabhaChakraborty** [comment]
uhh after May 28th !?

**Comment by chebroluharika** [comment]
> uhh after May 28th !?

I presume this program ends by end of this month. So try to complete it asap

**Comment by ArkaprabhaChakraborty** [comment]
Doesn't matter to me... I don't do open source explicitly for such programmes. But yes if it matters to the organisation then I will try to complete it before the 28th. :)

**Comment by yvkrishna** [comment]
@ArkaprabhaChakraborty, when can you able to complete this task before the program ends?

**Comment by ArkaprabhaChakraborty** [comment]
There was a bug with getdataloader. Was it solved? Because this issue depends on that.

**Comment by chebroluharika** [comment]
Yes
