### ISSUE TITLE
Add Examples -Horses Vs Humans

### ISSUE THREAD

**Issue by yvkrishna** [flow2ml/Flow2ML#63]
Need to add examples for this library. Users can able to understand the usage of the library if they can have a few examples.
Also documenting the example code helps.

Before starting contributing to this issue it is necessary that to complete #55 and its sub-issues.

If data augmentation techniques have also been completed then we can complete this issue.

**Comment by noobkid2411** [comment]
Hi,I would like to work on adding the various examples required for the users,if data augmentation issue is done with. Can I work on the same?

**Comment by yvkrishna** [comment]
yeah @noobkid2411, You can work on it.

**Comment by noobkid2411** [comment]
Hey,thanks for responding.unfortunately I have a health emergency in my family to deal with.I would still like to contribute but I might not be able to make a pr before the 20th.If this is an urgent work,you can unassign me,sorry for the inconvenience from my side.

**Comment by yvkrishna** [comment]
> Hey,thanks for responding.unfortunately I have a health emergency in my family to deal with.I would still like to contribute but I might not be able to make a pr before the 20th.If this is an urgent work,you can unassign me,sorry for the inconvenience from my side.


No problem.

We will look into that.

Be safe

**Comment by a-ma-n** [comment]
Can I help with this issue?
Also, can I show an example of a CNN  for this issue?

**Comment by chebroluharika** [comment]
@a-ma-n do we have any update on this?

**Comment by a-ma-n** [comment]
on it I'm just trying to use the library we need  which is necessary for augumentation

**Comment by a-ma-n** [comment]
@chebroluharika do I need to run it on a model or just applying the filters is sufficient?

**Comment by chebroluharika** [comment]
> @chebroluharika do I need to run it on a model or just applying the filters is sufficient?

@a-ma-n use this library for end-to-end model training
Prepare dataset using getDataset() and apply required filters and augmentations present in this library, train model (any model because model training is not yet implemented in this library yet), then take that model and predict on test set, import results like roc-auc curve, confusion matrix using AutoResults present in this library.
Hope I am clear to you.

**Comment by a-ma-n** [comment]
Sure I got the idea I'll get working on it,
I'm getting this  error 
AttributeError: 'Flow' object has no attribute 'applyAugmentation'
I was able to apply filter but not augmentation could you help me with this

**Comment by a-ma-n** [comment]
Sorry I have an urgent medical condition at home, I don't think ill be able to continue
Thanks for your time and patience.

**Comment by chebroluharika** [comment]
> Sorry I have an urgent medical condition at home, I don't think ill be able to continue
> Thanks for your time and patience.

Np. Take care @a-ma-n
