### ISSUE TITLE
Implement Morphological Transformations for images

### ISSUE THREAD

**Issue by chebroluharika** [flow2ml/Flow2ML#65]
Implement Morphological Transformations for images like

1. Erosion
2. Dilation
3. Opening
4. Closing

**Comment by ainy-123** [comment]
I am GSSoC'21 participant.I want to work on this issue.
Will you please assign this to me?

> Implement Morphological Transformations for images like
> 
> 1. Erosion
> 2. Dilation
> 3. Opening
> 4. Closing

**Comment by chebroluharika** [comment]
@ainy-123 please go ahead
