### ISSUE TITLE
Complete visualizeFilters method in Filters.py File

### ISSUE THREAD

**Issue by yvkrishna** [flow2ml/Flow2ML#66]
[In Filters.py file](https://github.com/flow2ml/Flow2ML/blob/main/flow2ml/Filters.py) At last there is a method named visualizeFilters(). 

In general, if a user tries to apply few filters then their respective image data would be stored in processedData folder.
As part of this issue, we need to take an original sample image and their filtered versions and plot the original image vs filtered versions of that image in a single plot. The input to that method would be the filters selected by the user.

I am attaching the expected output after completing this issue. The image is a color image. We can neglect Hog Feature and keep other filters selected by the user

![sample image](https://user-images.githubusercontent.com/49089434/116507163-5e1a8580-a8dc-11eb-8589-38686d43b82f.png)

**Comment by rubyruins** [comment]
For this issue, how to decide on which image to pick? Also, do this plot need to be saved as an image?

**Comment by yvkrishna** [comment]
> For this issue, how to decide on which image to pick? Also, do this plot need to be saved as an image?

We need to select an image randomly. 
Yeah we need to save it where we used to save the pre-processing document.
