### ISSUE TITLE
Improve code standards as per PEP8

### ISSUE THREAD

**Issue by chebroluharika** [flow2ml/Flow2ML#70]
Modify entire code as per PEP8 standard

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by chebroluharika** [comment]
@AshuKV please go ahead and work on it. When can we expect deliverable?

**Comment by AshuKV** [comment]
Thanks @chebroluharika, I would send a PR for this issue within 4-5 days.
