### ISSUE TITLE
Add exception handing for os related commands

### ISSUE THREAD

**Issue by chebroluharika** [flow2ml/Flow2ML#72]
Add proper exception handling for os related commands
os.mkdir() - it creates a new directory in given specific path. 

Now let's say, what if directory with that given name already exists?
Create a utility function with below mentioned pipeline and call this function wherever you want to create a new directory using os.mkdir()
Display a message on console saying "Directory with same name already exists, do you want me to delete it and create a new one", if user gives input as "Y", then remove that old directory and create it again, else if user input is "N", then display a message "Please provide me another name for directory", then create a directory with that new proposed name.

**Comment by srisatya1197** [comment]
@chebroluharika I want to work on this issue.

**Comment by chebroluharika** [comment]
@srisatya1197 yes please goahead!
When can we expect output?

**Comment by srisatya1197** [comment]
Thank you @chebroluharika I'll make pr day after tommorrow.

**Comment by chebroluharika** [comment]
@srisatya1197 do we have any update on this?

**Comment by srisatya1197** [comment]
Sorry @chebroluharika I couldn't complete. I'm booked with other work.
