### ISSUE TITLE
Add automated analysis support for tensorflow models 

### ISSUE THREAD

**Issue by ArkaprabhaChakraborty** [flow2ml/Flow2ML#75]
- [x] I checked to make sure that this issue has not already been filed.

- [x] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

# Expected Behavior:
There should be a class for automated evaluation of tensorflow models that will accept the model's history as an input and make the roc curves, confusion matrix and pr curves. The class can have an additional method to create a doc file with those plots. 

# Solution: 
Similar to like Auto_Results class.

**Comment by yvkrishna** [comment]
@ArkaprabhaChakraborty, I am assigning this to you.

**Comment by ArkaprabhaChakraborty** [comment]
Roger that !!

**Comment by ArkaprabhaChakraborty** [comment]
By may 17th
