### ISSUE TITLE
Deploying tensorflow models

### ISSUE THREAD

**Issue by yvkrishna** [flow2ml/Flow2ML#76]
You will be having the TensorFlow model trained using the data.
As part of this issue, we need to automate the process of model deployment using TensorFlow method like tfjs.converters.save_keras_model()

As part of this issue,

1. we need to use the flow.py file.
2. We need to have deploy_tensorflow_model() as a class method in it which can be used to convert the input model to tfjs model or tflite model based on user inputs.

Later we can try to include various other frameworks as well.

**Comment by ainy-123** [comment]
I am GSSoC'21 participant. I want to work on this issue.
kindly assign this to me.

**Comment by yvkrishna** [comment]
@ainy-123, you can start working on it

**Comment by ainy-123** [comment]
> @ainy-123, you can start working on it

Thanks for assigning . @yvkrishna

**Comment by chebroluharika** [comment]
@ainy-123 when can we expect output?

**Comment by chebroluharika** [comment]
@ainy-123 any update?

**Comment by yvkrishna** [comment]
@ainy-123 can you please update your work here.
The deadline is approaching !!!

**Comment by ainy-123** [comment]
> @ainy-123 can you please update your work here.
> The deadline is approaching !!!

sorry for delay ,kindly review and merge the PR.

**Comment by yvkrishna** [comment]
Closing this issue. Will reopen if there are any new changes

**Comment by chebroluharika** [comment]
@yvkrishna PR for this is not yet merged. Hence, reopening it.

**Comment by yvkrishna** [comment]
> @yvkrishna PR for this is not yet merged. Hence, reopening it.

Okay sry 😬
