### ISSUE TITLE
Contribution for GSSOC

### ISSUE THREAD

**Issue by rubyruins** [flow2ml/Flow2ML#8]
Hi, I would love to contribute to this project during GSSOC 21. Could you tell me a bit more about the progress on the project and what sort of features you expect us to implement?

**Comment by yvkrishna** [comment]
Hello @rubyruins,
Till now, we have implemented loading the data from the dataset folder, applied filters to it, and then load them as datasets. For GSSOC 21, At present We plan to implement data augmentation techniques and then testing the entire code base till now.

**Comment by rubyruins** [comment]
@yvkrishna that sounds good! I would like to contribute to it. Would you be creating issues from your side so that we can assign ourselves to them? Also, is there any group for discussion of this project?

**Comment by Ananya88** [comment]
Hey !!
I am interested in this project as GSSOC '21 participant .
And I would like to to update the Readme.md file by adding :

1.How to contribute in this project. The procedure from forking to making a pull request.
2.About how to add issues and etc.
Please assign me with this issue .Thanks.

**Comment by annapurnavinod** [comment]
Hi, I would love to contribute to this project. Please comment on what all issues are to be worked on.

**Comment by feni-katharotiya** [comment]
@rubyruins  Hello, I am gssoc participant and would like to work on this issue.

**Comment by yvkrishna** [comment]
> Hey !!
> I am interested in this project as GSSOC '21 participant .
> And I would like to to update the Readme.md file by adding :
> 
> 1.How to contribute in this project. The procedure from forking to making a pull request.
> 2.About how to add issues and etc.
> Please assign me with this issue .Thanks.

Thanks for that. But that is the role of project admins and mentors. But you can send it to me, I would discuss it with the project mentors as well and update it. :smile:

**Comment by yvkrishna** [comment]
> Hi, I would love to contribute to this project. Please comment on what all issues are to be worked on.

Yep, We are adding the issues one by one.
Till now we have added the main things, you can start working on them

**Comment by Polokghosh53** [comment]
Hello @yvkrishna, my name is Polok Ghosh and I am from the GSSoC '21 program. I have done a PR can you please look into it. It just a improvisation of the README, could you please review it. 
Thank you.

**Comment by Pranjal-2001** [comment]
Hey! I am a GSSoC participant.
Will you be adding new issues?

**Comment by yvkrishna** [comment]
> Hey! I am a GSSoC participant.
> Will you be adding new issues?

Hello @Pranjal-2001  good to see you here. Yeah we would be adding more issue in comming times

**Comment by Elizah550** [comment]
Hey !!
 I want to work on this issue and keep contribute how much as I can through this learning process.
Please assign me with this issue .Thanks.

**Comment by Dhriti-Roy** [comment]
I am a Gssoc'21 participant , I would like to work on it . Kindly assigned it to me.

**Comment by yvkrishna** [comment]
thanks @Elizah550  and @Dhriti-Roy  for your intrest. You can start contributing, we will assign the members for the second round for girl script summer of code. 😃
