### ISSUE TITLE
Requirements not updated

### ISSUE THREAD

**Issue by rubyruins** [flow2ml/Flow2ML#83]
### **Describe the bug:**
Running `pip install -r requirements.txt` gives the following error:

![image](https://user-images.githubusercontent.com/50259869/118534533-f92daf00-b766-11eb-8318-2424f1664562.png)

### **To Reproduce:**
Please provide the steps to reproduce this bug/error:
This issue is faced when working in a virtual environment and trying to run any sample code from this package.  I think there are a few packages that are not yet updated in the requirements. The code in question is given below and was previously working before merging with the upstream.

```
from flow2ml import Flow

flow = Flow( 'dataset_dir' , 'data_dir' )
operations = {'crop': [50, 100, 50, 100]}
flow.applyAugmentation( operations )
```

### **Expected behavior:**
The code should run smoothly and free of errors after installing all the requirements. 

<hr/>

**Comment by chebroluharika** [comment]
@ArkaprabhaChakraborty can you look into this

**Comment by ArkaprabhaChakraborty** [comment]
got it
