### ISSUE TITLE
Implement Histogram Equalisation as a part of Augmentations

### ISSUE THREAD

**Issue by chebroluharika** [flow2ml/Flow2ML#86]
Create a class:`HistogramEqualisation` In Data_Augmentations.py to perform histogram    equalisation on images.

**Comment by ainy-123** [comment]
I am GSSoC'21 participant and I want to work on this issue.
Will you please assign this to me?

> Create a class:`HistogramEqualisation` In Data_Augmentations.py to perform histogram equalisation on images.

**Comment by chebroluharika** [comment]
@ainy-123 please go ahead and work on it. 
can you please let us know about when can we expect deliverable for this to be out?

**Comment by ainy-123** [comment]
> @ainy-123 please go ahead and work on it.
> can you please let us know about when can we expect deliverable for this to 

> @ainy-123 please go ahead and work on it.
> can you please let us know about when can we expect deliverable for this to be out?

latest by tomorrow .I will try to make PR today itself asap.
