### ISSUE TITLE
Implement a functionality to convert images to Greyscale as part of Augmentations

### ISSUE THREAD

**Issue by chebroluharika** [flow2ml/Flow2ML#87]
This class is used to convert images into greyscale. That is, it converts    images into having only shades of grey (pixel value intensities)    varying from 0 to 255 which represent black and white respectively.

**Comment by rubyruins** [comment]
Hi @chebroluharika, I would like to work on this after the completion of #41 since the issues are related. Is it okay?

**Comment by chebroluharika** [comment]
@rubyruins yes, please go ahead
