### ISSUE TITLE
Implement Enhance brightness for images as apart of Augmentations

### ISSUE THREAD

**Issue by chebroluharika** [flow2ml/Flow2ML#88]
Implement a class to enhance image brightness  of a image

**Comment by prakharshreyash15** [comment]
Can you please assign me this issue?

**Comment by chebroluharika** [comment]
Hi @prakharshreyash15 please go ahead and work on this.
When can we expect output for this?

**Comment by chebroluharika** [comment]
As contrast is already implemented using CLAHE and its already merged, I removed contrast functionality from this issue. 
@prakharshreyash15 Hence, please work on only enhancing brighness of image.

**Comment by A-kriti** [comment]
@chebroluharika ma'am, Are u looking for something like shown below to adjust the contrast of an image accordingly!!

![Screenshot (402)](https://user-images.githubusercontent.com/73133055/119390554-d4978100-bcea-11eb-8d06-76bf48f04d61.png)

If yes!, then pls assign this to me as I used a different method other than CLAHE...

**Comment by ainy-123** [comment]
> As contrast is already implemented using CLAHE and its already merged, I removed contrast functionality from this issue.
> @prakharshreyash15 Hence, please work on only enhancing brighness of image.

hey @chebroluharika ,Can I work on this issue?

**Comment by chebroluharika** [comment]
@ainy-123 yes, you can work as we didn’t hear any update from @prakharshreyash15 from long back

**Comment by rubyruins** [comment]
Has this issue been completed?

**Comment by chebroluharika** [comment]
No @rubyruins
