### ISSUE TITLE
Data Augumentation

### ISSUE THREAD

**Issue by yvkrishna** [flow2ml/Flow2ML#9]
Data augmentation plays one of the key roles in any ml project. So need to implement data augumentation techniques such as 

1. Flipping
2. Rotation
3. Shearing
4. Cropping
5. Zoom in, Zoom out
6. scaling

**Comment by rubyruins** [comment]
Hi, I would like to work on this for GSSOC! Could you guide me as to how I can help implement this?

**Comment by yvkrishna** [comment]
@rubyruins For implementing these features we need to know OpenCV functions related to the above-mentioned features and write corresponing methods similar to methods in the filters class.

**Comment by rubyruins** [comment]
I would like to work on this issue. I have used OpenCV before, but I'll need some time to understand how the codebase works and how we can implement this. Could you please assign it to me? Also, will there be any official discussion about the project after the project channels are open to everyone?

**Comment by yvkrishna** [comment]
> I would like to work on this issue. I have used OpenCV before, but I'll need some time to understand how the codebase works and how we can implement this. Could you please assign it to me? Also, will there be any official discussion about the project after the project channels are open to everyone?

Oh great to hear. Yeah, you can start contributing to this issue and our team would check it. 
Yes, we will have an official discussion.

**Comment by rubyruins** [comment]
@yvkrishna Cool! Can we connect on Discord when the project channels open for all participants? Also, should I wait to contribute to this issue until we have a discussion for this project on the server?

**Comment by yvkrishna** [comment]
> @yvkrishna Cool! Can we connect on Discord when the project channels open for all participants? Also, should I wait to contribute to this issue until we have a discussion for this project on the server?

yeah, we would connect through discord and you can start working on it and regularly update the team so that we can see that you are in the correct direction.

**Comment by subhanjan160901** [comment]
Is this issue closed? If not, I would want to work on it

**Comment by chebroluharika** [comment]
@subhanjan160901 this is live. Please go ahead and work on it
Raise PR with fix once its done. Thanks.

**Comment by yvkrishna** [comment]
@rubyruins any update regarding this issue ?

**Comment by rubyruins** [comment]
I think @subhanjan160901 is assigned to this and working on it.. if not I will be happy to take this issue up.

**Comment by Rajeswari0410** [comment]
If this issue is not done then i would like to work on it

**Comment by yvkrishna** [comment]
I think @subhanjan160901 is inactive. @chebroluharika, I think we can assign this issue to others.

**Comment by chebroluharika** [comment]
Sure @yvkrishna

**Comment by yvkrishna** [comment]
@Rajeswari0410 @rubyruins anyone of you can take up this issue. 👍

**Comment by rubyruins** [comment]
I would like to give it a try. So we need to add the Flipping, Rotation, Shearing, Cropping, Zoom in, Zoom out, scaling functions to it, right?

**Comment by yvkrishna** [comment]
> I would like to give it a try. So we need to add the Flipping, Rotation, Shearing, Cropping, Zoom in, Zoom out, scaling functions to it, right?

okay 👍

**Comment by yvkrishna** [comment]
re initializing the same issue
