### ISSUE TITLE
Create connection between Augmentations and Filters

### ISSUE THREAD

**Issue by chebroluharika** [flow2ml/Flow2ML#92]
Right now, filters and augmentations work on original images.
But if user wants to apply filters on augmentated images, which is not implemented.
Now implement code for 
1. Create connection between filters.py and Augmentations.py in such a way that user should be able to apply filters on augmented images(those are stored in ProcessedData folder)

**Comment by rubyruins** [comment]
Hi @chebroluharika, actually the processedData folder only gets formed when we split into train and test, that is on calling:
(train_x, train_y, val_x, val_y) = flow.getDataset( img_dimensions, test_val_split )

Without calling getDataset if we just want to augment and filter images, processedData folder does not get created using those functions.

**Comment by chebroluharika** [comment]
> Hi @chebroluharika, actually the processedData folder only gets formed when we split into train and test, that is on calling:
> (train_x, train_y, val_x, val_y) = flow.getDataset( img_dimensions, test_val_split )
> 
> Without calling getDataset if we just want to augment and filter images, processedData folder does not get created using those functions.

Yes @rubyruins 
Here we need code for after applying augmentations if user want to apply filters on them, he should be able to do it and viceversa

**Comment by chebroluharika** [comment]
> > Hi @chebroluharika, actually the processedData folder only gets formed when we split into train and test, that is on calling:
> > (train_x, train_y, val_x, val_y) = flow.getDataset( img_dimensions, test_val_split )
> > Without calling getDataset if we just want to augment and filter images, processedData folder does not get created using those functions.
> 
> Yes @rubyruins
> Here we need code for after applying augmentations if user want to apply filters on them, he should be able to do it and viceversa

something like take list of files/path of file to which operations needs to be applied as input to applyFilters() may work.
