### ISSUE TITLE
Updation of Pull Request Template 

### ISSUE THREAD

**Issue by darpankhanna** [flow2ml/Flow2ML#94]
I want to update this template and make it similar to Theos template.

**Comment by darpankhanna** [comment]
@chebroluharika  can u please assign me this issue

**Comment by chebroluharika** [comment]
@darpankhanna please update the description of this issue like what you want to change in PR template?

**Comment by chebroluharika** [comment]
@darpankhanna thanks for updating description. Can you please make me understand for necessity of this change when there is already a pullrequest template is in place.

**Comment by chebroluharika** [comment]
As I don't see response from @darpankhanna, closing it.
@yvkrishna , @darpankhanna if you really think that this issue makes sense, please feel free to reopen it.
